"""Public package exports for SummonerIdentity and related identity helpers."""

from .host import IdentityHostMixin, IDENTITY_HOST_VERSION

# Re-export the public API from identity.
from .identity import (
    SummonerIdentity,
    SummonerIdentityControls,
    b64_decode,
    b64_encode,
    ENV_VERSION,
    HISTORY_PROOF_VERSION,
    ID_VERSION,
    IDENTITY_CONTROLS_VERSION,
    PAYLOAD_ENC_VERSION,
    PEER_KEYS_STORE_VERSION,
    REPLAY_STORE_VERSION,
    SESSIONS_STORE_VERSION,
    derive_history_proof_key,
    derive_payload_key,
    derive_sym_key,
    hist_next,
    id_fingerprint,
    load_identity,
    serialize_public_key,
    save_identity,
    session_summary,
    sign_bytes,
    sign_public_id,
    verify_bytes,
    verify_public_id,
)

__all__ = [
    "IdentityHostMixin",
    "IDENTITY_HOST_VERSION",
    "IDENTITY_CONTROLS_VERSION",
    "SummonerIdentity",
    "SummonerIdentityControls",
    "ID_VERSION",
    "ENV_VERSION",
    "PAYLOAD_ENC_VERSION",
    "HISTORY_PROOF_VERSION",
    "SESSIONS_STORE_VERSION",
    "PEER_KEYS_STORE_VERSION",
    "REPLAY_STORE_VERSION",
    "b64_encode",
    "b64_decode",
    "serialize_public_key",
    "sign_bytes",
    "verify_bytes",
    "id_fingerprint",
    "sign_public_id",
    "verify_public_id",
    "save_identity",
    "load_identity",
    "session_summary",
    "hist_next",
    "derive_sym_key",
    "derive_history_proof_key",
    "derive_payload_key",
]
